"use client";

import { useState, useEffect } from "react";
import Header from "@/components/shared/Header";
import { fetchRecommendations, CarbonProfile, CalculationResult, CoachResponse } from "@/lib/api";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Sparkles, Send, User, Bot, RefreshCw 
} from "lucide-react";

interface ChatMessage {
  id: string;
  sender: "user" | "coach";
  text: string;
  timestamp: Date;
}

const INITIAL_PROFILE: CarbonProfile = {
  transportation: { milesPerWeek: 120, vehicleType: "gas" },
  diet: { dietType: "low_meat" },
  energy: { kwhPerMonth: 450, source: "grid" },
  shopping: { newClothesPerMonth: 3, techUpgradesPerYear: 2 }
};

export default function CoachPage() {
  const [profile] = useState<CarbonProfile>(INITIAL_PROFILE);
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState<{ calculated_profile: CalculationResult, ai_coach_response: CoachResponse } | null>(null);

  // Chat states
  const [chatInput, setChatInput] = useState("");
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [isAiTyping, setIsAiTyping] = useState(false);

  const loadCoachRecommendations = async () => {
    setLoading(true);
    try {
      const recommendations = await fetchRecommendations(profile);
      setData(recommendations);
      
      // Seed first coach greeting if chat is empty
      if (chatMessages.length === 0) {
        setChatMessages([
          {
            id: "greeting",
            sender: "coach",
            text: `Hello! I'm your Sustainability Coach. Based on your current Carbon Twin footprint (${recommendations.calculated_profile.total_kg} kg CO₂/mo), your Eco Score is estimated to be ${recommendations.ai_coach_response.eco_score_estimate}. How can I help you reduce your footprint today?`,
            timestamp: new Date()
          }
        ]);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    const timer = setTimeout(() => {
      loadCoachRecommendations();
    }, 0);
    return () => clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleSendChat = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim()) return;

    const userMsg: ChatMessage = {
      id: `user-${Date.now()}`,
      sender: "user",
      text: chatInput,
      timestamp: new Date()
    };

    setChatMessages(prev => [...prev, userMsg]);
    setChatInput("");
    setIsAiTyping(true);

    // Call mock coach feedback response after brief delay
    setTimeout(() => {
      let coachResponseText = "That is a great question. ";
      const textLower = userMsg.text.toLowerCase();
      
      if (textLower.includes("transport") || textLower.includes("car") || textLower.includes("drive")) {
        coachResponseText += "Reducing transportation footprint offers direct returns. Consider public transport, driving hybrid modes, or consolidating weekly errands to save miles.";
      } else if (textLower.includes("eat") || textLower.includes("diet") || textLower.includes("food") || textLower.includes("meat")) {
        coachResponseText += "Switching even a few meals from red meat to plant-based proteins lowers overall agricultural demand, which is a significant factor in high-impact lifestyle reductions.";
      } else if (textLower.includes("solar") || textLower.includes("energy") || textLower.includes("electric")) {
        coachResponseText += "Transitioning to solar decreases grid reliance by near 95% depending on utility load. Try shifting smart appliance runs to sunny peak hours.";
      } else {
        coachResponseText += "Every small choice compounds. Focus on reducing retail consumption and adjusting household temperature settings for easy wins.";
      }

      setChatMessages(prev => [...prev, {
        id: `coach-${Date.now()}`,
        sender: "coach",
        text: coachResponseText,
        timestamp: new Date()
      }]);
      setIsAiTyping(false);
    }, 1000);
  };

  return (
    <div className="flex flex-col min-h-screen bg-background text-foreground font-sans">
      <Header />

      <main className="flex-1 mx-auto max-w-7xl w-full px-4 py-8 sm:px-6 lg:px-8">
        
        {/* Page Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-extrabold tracking-tight text-foreground flex items-center gap-2">
            <Sparkles className="text-accent h-8 w-8" />
            AI Sustainability <span className="text-primary">Coach</span>
          </h1>
          <p className="mt-2 text-sm text-foreground/75 max-w-2xl">
            Review personalized recommendations generated by Google Gemini and discuss direct actions you can take today.
          </p>
        </div>

        {/* Main Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          
          {/* Left Column: Recommendations & Drivers (7 cols) */}
          <div className="lg:col-span-7 space-y-6">
            
            {/* Loading placeholder */}
            {loading && !data && (
              <div className="flex flex-col items-center justify-center py-20 text-foreground/60 gap-3">
                <RefreshCw className="h-10 w-10 animate-spin text-primary" />
                <p className="text-sm font-semibold">Consulting Gemini Coach...</p>
              </div>
            )}

            {data && (
              <>
                {/* Eco Score & Driver Panel */}
                <div className="glass-card rounded-2xl p-6 glow-on-hover grid grid-cols-1 sm:grid-cols-3 gap-6">
                  {/* Score */}
                  <div className="flex flex-col items-center justify-center text-center border-b sm:border-b-0 sm:border-r border-border pb-4 sm:pb-0 sm:pr-4">
                    <span className="text-xs font-semibold text-foreground/60 uppercase tracking-wider mb-1">
                      Eco Score
                    </span>
                    <div className="relative flex items-center justify-center">
                      <div className="h-24 w-24 rounded-full border-4 border-primary/20 flex items-center justify-center">
                        <span className="text-4xl font-extrabold text-primary">
                          {data.ai_coach_response.eco_score_estimate}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Highlights */}
                  <div className="sm:col-span-2 space-y-3">
                    <h3 className="font-bold text-sm text-foreground">Analysis Brief</h3>
                    <p className="text-xs text-foreground/80 leading-relaxed">
                      {data.ai_coach_response.analysis}
                    </p>
                    {data.ai_coach_response.primary_drivers.length > 0 && (
                      <div className="pt-2">
                        <span className="text-[10px] font-bold text-red-400 uppercase tracking-wider block mb-1">
                          Primary Footprint Drivers
                        </span>
                        <div className="flex flex-wrap gap-1.5">
                          {data.ai_coach_response.primary_drivers.map((driver, idx) => (
                            <span key={idx} className="px-2 py-0.5 text-xs rounded-full bg-red-500/10 text-red-400 border border-red-500/20 font-semibold">
                              {driver}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>

                {/* Recommendations Title */}
                <div>
                  <h3 className="font-bold text-lg text-foreground mb-4">Your Reduction Plan</h3>
                  <div className="space-y-4">
                    {data.ai_coach_response.recommendations.map((rec, index) => (
                      <motion.div
                        initial={{ opacity: 0, y: 15 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: index * 0.1 }}
                        key={index}
                        className="glass-card rounded-2xl p-5 glow-on-hover border-l-4 border-l-primary flex flex-col md:flex-row md:items-start justify-between gap-4"
                      >
                        <div className="space-y-2">
                          <h4 className="font-bold text-base text-foreground leading-tight">
                            {rec.action}
                          </h4>
                          <p className="text-xs text-foreground/70 leading-relaxed max-w-xl">
                            {rec.explanation}
                          </p>
                          
                          {/* Parameter Badges */}
                          <div className="flex flex-wrap gap-2 pt-2">
                            <span className={`px-2.5 py-0.5 text-[10px] font-bold rounded-full uppercase ${
                              rec.impact === "high" ? "bg-green-500/10 text-green-400 border border-green-500/20" :
                              rec.impact === "medium" ? "bg-yellow-500/10 text-yellow-400 border border-yellow-500/20" :
                              "bg-slate-500/10 text-slate-400 border border-slate-500/20"
                            }`}>
                              Impact: {rec.impact}
                            </span>
                            <span className="px-2.5 py-0.5 text-[10px] font-bold rounded-full uppercase bg-secondary text-foreground/80 border border-border">
                              Cost: {rec.cost}
                            </span>
                            <span className="px-2.5 py-0.5 text-[10px] font-bold rounded-full uppercase bg-secondary text-foreground/80 border border-border">
                              Difficulty: {rec.difficulty}
                            </span>
                          </div>
                        </div>

                        {/* Reduction Metric */}
                        <div className="flex flex-row md:flex-col items-baseline md:items-end justify-between md:justify-center border-t md:border-t-0 border-border pt-3 md:pt-0 shrink-0">
                          <span className="text-[10px] font-bold text-foreground/60 uppercase tracking-wider">
                            Est. Savings
                          </span>
                          <span className="text-xl font-extrabold text-primary">
                            -{Math.round(rec.estimated_annual_savings_kg)} kg/yr
                          </span>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                </div>
              </>
            )}

          </div>

          {/* Right Column: Interactive Coach Chat (5 cols) */}
          <div className="lg:col-span-5 h-[600px] flex flex-col glass-card rounded-2xl overflow-hidden border border-border">
            
            {/* Chat Title bar */}
            <div className="px-4 py-3 border-b border-border bg-card flex items-center gap-2">
              <Bot className="h-5 w-5 text-accent" />
              <div>
                <h3 className="font-bold text-sm text-foreground">Coaching Thread</h3>
                <span className="text-[10px] text-green-400 font-semibold flex items-center gap-1">
                  <span className="h-1.5 w-1.5 rounded-full bg-green-400 animate-pulse"></span>
                  Active coach agent online
                </span>
              </div>
            </div>

            {/* Message Thread Area */}
            <div className="flex-1 p-4 overflow-y-auto space-y-4">
              <AnimatePresence initial={false}>
                {chatMessages.map((msg) => {
                  const isCoach = msg.sender === "coach";
                  return (
                    <motion.div
                      key={msg.id}
                      initial={{ opacity: 0, x: isCoach ? -10 : 10 }}
                      animate={{ opacity: 1, x: 0 }}
                      className={`flex gap-3 max-w-[85%] ${
                        isCoach ? "mr-auto" : "ml-auto flex-row-reverse"
                      }`}
                    >
                      {/* Avatar */}
                      <div className={`h-8 w-8 rounded-full flex items-center justify-center shrink-0 border ${
                        isCoach ? "bg-accent/10 border-accent/20 text-accent" : "bg-primary/10 border-primary/20 text-primary"
                      }`}>
                        {isCoach ? <Bot className="h-4 w-4" /> : <User className="h-4 w-4" />}
                      </div>

                      {/* Bubble */}
                      <div className={`p-3 rounded-2xl text-xs leading-relaxed ${
                        isCoach 
                          ? "bg-secondary text-foreground/90 rounded-tl-none border border-border" 
                          : "bg-primary text-primary-foreground rounded-tr-none font-medium"
                      }`}>
                        {msg.text}
                      </div>
                    </motion.div>
                  );
                })}
              </AnimatePresence>

              {isAiTyping && (
                <div className="flex gap-3 max-w-[80%]">
                  <div className="h-8 w-8 rounded-full flex items-center justify-center shrink-0 border bg-accent/10 border-accent/20 text-accent">
                    <Bot className="h-4 w-4" />
                  </div>
                  <div className="bg-secondary p-3 rounded-2xl rounded-tl-none border border-border flex items-center gap-1">
                    <span className="h-1.5 w-1.5 bg-foreground/60 rounded-full animate-bounce"></span>
                    <span className="h-1.5 w-1.5 bg-foreground/60 rounded-full animate-bounce [animation-delay:0.2s]"></span>
                    <span className="h-1.5 w-1.5 bg-foreground/60 rounded-full animate-bounce [animation-delay:0.4s]"></span>
                  </div>
                </div>
              )}
            </div>

            {/* Input Form */}
            <form onSubmit={handleSendChat} className="p-3 border-t border-border bg-card flex gap-2">
              <input
                type="text"
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                placeholder="Ask coach for custom tips..."
                className="flex-1 px-3 py-2 text-xs bg-background rounded-lg border border-border focus:outline-none focus:border-primary transition-colors text-foreground"
              />
              <button
                type="submit"
                className="p-2 rounded-lg bg-primary text-primary-foreground hover:bg-primary/90 transition-colors shrink-0"
              >
                <Send className="h-4 w-4" />
              </button>
            </form>

          </div>

        </div>

      </main>
    </div>
  );
}
